 # Day1
 Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

In [1]:
import numpy as np 

In [13]:
a = np.array([1,2,3],dtype='int16')
b = np.array([[4.0,5.0,6.0],[7.0,8.0,9.0]])

In [ ]:
print("# det dimension of array")
print(a.ndim)
print(b.ndim)
print("#get shape of array")
print(a.shape)  
print(b.shape)
print("#get type of array")
print(a.dtype)
print(b.dtype)
print("#get size of array")
print(a.itemsize)
print(b.itemsize)
print("#get total size of array")
print(a.nbytes)       # 3*2 = 6
print(b.nbytes)        # 3*2*8 = 48

# det dimension of array
1
2
#get shape of array
(3,)
(2, 3)
#get type of array
int16
float64
#get size of array
2
8
#get total size of array
6
48


Accessing/Changing specific elements, rows, columns, etc

2D array:

In [27]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
# Get a specific element [row,column]
print(a[1,5])

13


In [30]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# get a specific column
a[:,2]

array([ 3, 10])

In [35]:
# getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [42]:
a[1,5] = 20
print(a)
a[:,2] = [5,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3D-example

In [49]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [51]:
# Get specific element (work outside in)
b[:,1,:]

array([[3, 4],
       [7, 8]])

Initializing Different Types of Arrays

In [56]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
# All 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)