**Pandas**

Ex01-Q1

In [84]:
import numpy as np 
import pandas as pd
import random

Q2

In [85]:
first_rand = np.random.randint(1,4,size=100)
first_rand

array([3, 2, 3, 2, 1, 3, 1, 1, 2, 3, 3, 2, 1, 1, 3, 1, 1, 1, 2, 1, 1, 1,
       1, 3, 2, 1, 3, 3, 2, 1, 2, 1, 2, 3, 3, 3, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 3, 2, 1, 2, 2, 1, 2, 2, 3, 1, 3, 3, 2, 3, 2, 2, 1, 3, 1,
       1, 2, 1, 1, 2, 1, 2, 2, 1, 3, 2, 3, 3, 1, 3, 2, 1, 2, 1, 2, 3, 3,
       2, 2, 3, 2, 1, 2, 3, 3, 3, 1, 1, 2], dtype=int32)

In [86]:
second_rand = np.random.randint(1,3,size=100)
second_rand

array([2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1,
       2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2,
       1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2,
       1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1], dtype=int32)

In [87]:
third_rand = np.random.randint(10000,30000,size=100)
third_rand

array([24935, 29782, 13475, 19629, 17862, 18220, 19188, 15876, 22099,
       24816, 29729, 16545, 22901, 29912, 16068, 26605, 27046, 16660,
       25802, 27266, 20297, 25894, 17181, 22525, 21508, 20507, 25575,
       12056, 18679, 19763, 26703, 19230, 27032, 12897, 22003, 21313,
       27832, 14536, 11924, 22771, 15200, 27577, 10186, 20622, 14714,
       24542, 18061, 10702, 26995, 28403, 29375, 29514, 22744, 24372,
       11312, 19741, 21889, 11055, 16450, 20792, 21397, 24797, 29379,
       17188, 14315, 28070, 11744, 11377, 25679, 24999, 18887, 29354,
       14400, 10695, 25060, 29050, 28321, 12466, 10139, 22104, 12758,
       27019, 20419, 18928, 29492, 17157, 20677, 17439, 21788, 15060,
       23884, 17112, 23282, 24071, 21247, 17312, 13221, 24893, 15463,
       23850], dtype=int32)

Q3: create a DataFrame by combine the Series by column

In [88]:
my_data = pd.DataFrame({'first': first_rand, 'second': second_rand, 'third': third_rand})
my_data

first  second  third
0       3       2  24935
1       2       1  29782
2       3       2  13475
3       2       1  19629
4       1       2  17862
..    ...     ...    ...
95      3       2  17312
96      3       1  13221
97      1       2  24893
98      1       2  15463
99      2       1  23850

[100 rows x 3 columns]

Q4

In [89]:
my_data.columns = ["bedrs", "bathrs", "price_sqr_meter"]
my_data.head(10)

bedrs  bathrs  price_sqr_meter
0      3       2            24935
1      2       1            29782
2      3       2            13475
3      2       1            19629
4      1       2            17862
5      3       2            18220
6      1       2            19188
7      1       2            15876
8      2       1            22099
9      3       1            24816

Q5

In [90]:
bigcolumns = pd.DataFrame({
    'bigcolums': pd.concat([my_data["bedrs"], my_data["bathrs"], my_data["price_sqr_meter"]]),
})
bigcolumns

bigcolums
0           3
1           2
2           3
3           2
4           1
..        ...
95      17312
96      13221
97      24893
98      15463
99      23850

[300 rows x 1 columns]

Ex02-Q1-Q2

In [91]:
df_student = pd.read_csv(f"C:\Programming for DS Y3-S2\student-mat.csv")
df_student.head(10)

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\hp\AppData\Local\Temp\ipykernel_17412\2168218285.py:1: SyntaxWarning: invalid escape sequence '\P'
  df_student = pd.read_csv(f"C:\Programming for DS Y3-S2\student-mat.csv")


school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4   at_home   teacher   
1     GP   F   17       U     GT3       T     1     1   at_home     other   
2     GP   F   15       U     LE3       T     1     1   at_home     other   
3     GP   F   15       U     GT3       T     4     2    health  services   
4     GP   F   16       U     GT3       T     3     3     other     other   
5     GP   M   16       U     LE3       T     4     3  services     other   
6     GP   M   16       U     LE3       T     2     2     other     other   
7     GP   F   17       U     GT3       A     4     4     other   teacher   
8     GP   M   15       U     LE3       A     3     2  services     other   
9     GP   M   15       U     GT3       T     3     4     other     other   

   ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0  ...      4        3      4     1     1      3        6   5   6   6  
1  ...      5        3      3     1     1      3        4   5   5   6  
2  ...      4        3      2     2     3      3       10   7   8  10  
3  ...      3        2      2     1     1      5        2  15  14  15  
4  ...      4        3      2     1     2      5        4   6  10  10  
5  ...      5        4      2     1     2      5       10  15  15  15  
6  ...      4        4      4     1     1      3        0  12  12  11  
7  ...      4        1      4     1     1      1        6   6   5   6  
8  ...      4        2      2     1     1      1        0  16  18  19  
9  ...      5        5      1     1     1      5        0  14  15  15  

[10 rows x 33 columns]

In [92]:
df_student.loc[:,"school":"guardian"] # loc is a function that allows us to select rows and columns by labels

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     reason guardian  
0    course   mother  
1    course   father  
2     other   mother  
3      home   mother  
4      home   father  
..      ...      ...  
390  course    other  
391  course   mother  
392  course    other  
393  course   mother  
394  course   father  

[395 rows x 12 columns]

Q4

In [93]:
def capitalize(s):
    return s.capitalize()


Q5

In [98]:
df_student["Mjob"]=df_student["Mjob"].apply(capitalize)
df_student["Fjob"]=df_student["Fjob"].apply(capitalize)
df_student


school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   At_home   Teacher   
1       GP   F   17       U     GT3       T     1     1   At_home     Other   
2       GP   F   15       U     LE3       T     1     1   At_home     Other   
3       GP   F   15       U     GT3       T     4     2    Health  Services   
4       GP   F   16       U     GT3       T     3     3     Other     Other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  Services  Services   
391     MS   M   17       U     LE3       T     3     1  Services  Services   
392     MS   M   21       R     GT3       T     1     1     Other     Other   
393     MS   M   18       R     LE3       T     3     2  Services     Other   
394     MS   M   19       U     LE3       T     1     1     Other   At_home   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        6   5   6   6  
1    ...      5        3      3     1     1      3        4   5   5   6  
2    ...      4        3      2     2     3      3       10   7   8  10  
3    ...      3        2      2     1     1      5        2  15  14  15  
4    ...      4        3      2     1     2      5        4   6  10  10  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
390  ...      5        5      4     4     5      4       11   9   9   9  
391  ...      2        4      5     3     4      2        3  14  16  16  
392  ...      5        5      3     3     3      3        3  10   8   7  
393  ...      4        4      1     3     4      5        0  11  12  10  
394  ...      3        2      3     3     3      5        5   8   9   9  

[395 rows x 33 columns]